### ISSUE TITLE
swiftenv instructions absent in README.md

### ISSUE THREAD

**Issue by MaxDesiatov** [kateinoigakukun/life-game-with-swiftwasm#1]
As far as I understand, neither `npm install` nor `npm run start` will download the appropriate toolchain, shouldn't `README.md` then include some instructions for installing `swiftenv` and a corresponding toolchain?

**Comment by kateinoigakukun** [comment]
Added!

**Comment by MaxDesiatov** [comment]
Would you mind if I share this repository on SwiftWasm Twitter then? 🙂

**Comment by kateinoigakukun** [comment]
@MaxDesiatov  Of course not!
